### ISSUE TITLE
Crash loop when using Child Bridges

### ISSUE THREAD

**Issue by devinjdawson** [pkmnct/homebridge-television-universal-control#13]
```
/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:108
    service.emit('error', new Error('Service name is already in use on the network'))
                          ^
Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:108:27)
    at Prober.done (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (node:events:394:28)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (node:events:394:28)
    at UDP.onMessage (node:dgram:931:8)

```

It works if I reset all my devices, clear the cache, and change the MAC and port, but the moment I restart the bridge for any reason, it will stop working, and go into a reset loop, giving me the above error.

**Comment by pkmnct** [comment]
Can you provide the configuration you used to recreate this?
